### ISSUE TITLE
AttributeError: BASE_LR_END

### ISSUE THREAD

**Issue by wokeyide1999** [megvii-research/ICD#2]
您好，我在命令python train_baseline.py --num-gpus 1 --config-file configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml 下可以正常运行并生成model_final.pth，但是在命令python3 train_distill.py --num-gpus 1 --config-file configs/Distillation-ICD/retinanet_R_50_R101_icd_FPN_1x.yaml OUTPUT_DIR output/icd_retinanet中，却报如下错误，可以请问您是什么原因吗？十分感谢！

Traceback (most recent call last):
  File "train_distill.py", line 462, in <module>
    launch(
  File "/home/sh/detectron2-main/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_distill.py", line 447, in main
    do_train(cfg, model, teacher, resume=args.resume)
  File "train_distill.py", line 152, in do_train
    teacher_sche = build_lr_scheduler(cfg.MODEL.DISTILLER, teacher_opt)
  File "/home/sh/detectron2-main/detectron2/solver/build.py", line 275, in build_lr_scheduler
    end_value = cfg.SOLVER.BASE_LR_END / cfg.SOLVER.BASE_LR
  File "/home/sh/anaconda3/lib/python3.8/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: BASE_LR_END
Segmentation fault (core dumped)

**Comment by AmoseKang** [comment]
感谢你的提问，这个问题是由于Detectron更新添加了一个新config导致的，参考：
[Support specifying end lr for WarmupCosineLR.](https://github.com/facebookresearch/detectron2/commit/e3053c14cfcce515de03d3093c0a7b4e734fa41f)
建议你暂时使用[detectron 0.5](https://github.com/facebookresearch/detectron2/archive/refs/tags/v0.6.zip)版本，不要使用最新版本，我们会尽快更新来解决这个问题。

**Comment by AmoseKang** [comment]
更新了一版readme，你可以参考新的安装命令。

**Comment by wokeyide1999** [comment]
> 感谢你的提问，这个问题是由于Detectron更新添加了一个新config导致的，参考： [Support specifying end lr for WarmupCosineLR.](https://github.com/facebookresearch/detectron2/commit/e3053c14cfcce515de03d3093c0a7b4e734fa41f) 建议你暂时使用[detectron 0.5](https://github.com/facebookresearch/detectron2/archive/refs/tags/v0.6.zip)版本，不要使用最新版本，我们会尽快更新来解决这个问题。

十分感谢！
