### ISSUE TITLE
1GPU下效果不理想

### ISSUE THREAD

**Issue by wokeyide1999** [megvii-research/ICD#3]
我的的实验环境不具备8GPU条件，于是我在detectron2的官方说明指导下，将8GPU下运行的情况改为1GPU运行的情况，我使用如下命令
`python train_baseline.py --num-gpus 1 --config-file configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025`
` python3 train_distill.py --num-gpus 1 --resume --config-file configs/Distillation-ICD/retinanet_R_50_R101_icd_FPN_1x.yaml OUTPUT_DIR output/icd_retinanet SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025`
我得到的baseline效果为AP = 25.149，得到的蒸馏结果为AP = 35.860，baseline效果远低于论文给出的37.4，蒸馏结果也与39.9有一定差距。
请问这个结果正常吗？
我怎么样才能在1个GPU上达到与论文接近的水平？
十分感谢！

**Comment by AmoseKang** [comment]
最好用相同的batch size，你可以尝试一下梯度累加的方式:
[https://cowarder.site/2019/10/29/Gradient-Accumulation/](https://cowarder.site/2019/10/29/Gradient-Accumulation/)

**Comment by AmoseKang** [comment]
补充一下，不同batch_size对应的训练轮数也不同，例如bs=16 在 90k  iteration 下使用了 1440k 张图片，如果使用bs=2，需要训练 720k 才能对齐。

**Comment by wokeyide1999** [comment]
> 

明白了，十分感谢您的解答！
