### ISSUE TITLE
scale information是什么

### ISSUE THREAD

**Issue by 2021SH** [megvii-research/ICD#5]
![image](https://user-images.githubusercontent.com/90555190/163704826-4347be9e-98cd-496b-908c-45d4ee9651f5.png)
1、如图，请问其中的scale information指代的是什么操作？
2、请问有没有只使用Identification和Localization，而没有scale information的实验数据？
3、Identification，Localization和scale information共同使用的数据仅比使用Localization和scale information增长了0.5个AP，这是否意味着中文所在设计的辅助优化任务仍然有待提升，Identification与Localization的配合并非最优！

**Comment by AmoseKang** [comment]
1. 图中的+scale 指的是添加了额外的尺度信息。
回顾在文章中，我们的方法将准确的标注框扰动为大致中心点和大致尺度，其中大致尺度为 One-hot vector 描述的大致大小，详见[code](https://github.com/megvii-research/ICD/blob/4b995a287f66844440ab27808710be750e9e6474/pytorch_release/models/utils.py#L399)，就是此处的scale信息。
尺度信息为辅助任务和query提供了额外的知识和先验，帮助query获得更准确的定位结果，同时加速收敛。

2. 没有，如（1）所述，辅助信息改变的是输入特征不是任务，没有办法单独优化。

3. 是的，我们的方法采用的Identification+localization只是一种比较intuitive的方式，拿目标检测任务比较关注的两种信息作为优化目标，相信会存在更好的设计。
在实际可视化和观察中，我们也发现学到的注意力有一些局限性（比如有的头可视化效果不明确），以及辅助任务不太好收敛，这些应当能通过更好的设计来解决。

**Comment by 2021SH** [comment]
感谢解答！
