### ISSUE TITLE
复现baseline有问题？

### ISSUE THREAD

**Issue by GuoYi0** [megvii-research/ICD#6]
您好，我用如下命令，复现baseline
train_baseline.py --num-gpus 8 --config-file configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml
最后得到的结果是
![image](https://user-images.githubusercontent.com/30315023/181752254-ce92a028-64d6-4d4d-994e-716fc5bd7be9.png)
即AP只有37.292，而该代码报的是37.4。是不是哪里超参改动了？

**Comment by GuoYi0** [comment]
按照1.5x重新训练了一下，AP又达到了38.282。。

**Comment by AmoseKang** [comment]
我核对了一下，确实有一点小区别，我们的baseline没有用clip_gradient，但为了稳定，蒸馏的时候所有算法都使用了。可以先把baseline里的[CLIP_GRADIENTS: {"ENABLED": True}](https://github.com/MegEngine/ICD/blob/a97e0ecd9b69dbc0e3c2b8168c1d72ea79c6641b/pytorch_release/configs/Base-RetinaNet.yaml#L23)注释掉，我们后续会更新。
另外0.1AP的差异基本在误差范围内，可能再跑一次就能得到差不多的点。

**Comment by GuoYi0** [comment]
感谢大神，我试试
